import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LastPassFix from "@/app/common/components/last-pass-fix/last-pass-fix";
import MenuLightDarkModeSwitch
  from "@/app/common/components/menu/menu-light-dark-mode-switch/menu-light-dark-mode-switch";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LastPassFix>
          <MenuLightDarkModeSwitch/>
          {children}
        </LastPassFix>
      </body>
    </html>
  )
}
